all: generate build-cmd

build-cmd:
	go build cmd/demo-cleanarh/main.go

generate: \
	usecase

usecase: \
	usecase-auth \
	usecase-basket

usecase-basket:
	ifacemaker -c "Code generated by ifacemaker" \
            -f ./usecase/basket/basket.go \
            -s basketUseCase \
            -i BasketUseCase \
            -p usecase \
            -o ./usecase/basket.go

usecase-auth:
	ifacemaker -c "Code generated by ifacemaker" \
            -f ./usecase/auth/auth.go \
            -s authUseCase \
            -i AuthUseCase \
            -p usecase \
            -o ./usecase/auth.go

gateway: x

gateway-database:
	 ifacemaker -c "Code generated by ifacemaker" \
        -f ./gateway/database/basket.go \
        -s databaseGateway \
        -i BasketGateway \
        -p gateway \
        -o ./gateway/basket.go