// Code generated by ifacemaker

package usecase

import (
	"github.com/farwydi/demo-cleanarh/domain"
)

// AuthUseCase ...
type AuthUseCase interface {
	Login(fingerprint, login, password string) (*domain.User, error)
	Logout(*domain.User) error
	IsLogin(user *domain.User) (bool, error)
}
