// Code generated by ifacemaker

package usecase

import (
	"github.com/farwydi/demo-cleanarh/domain"
)

// BasketUseCase ...
type BasketUseCase interface {
	AddItem(user *domain.User, item *domain.Item) error
	RemoveItem(user *domain.User, item *domain.Item) error
	Cleanup(user *domain.User) error
	Buy(user *domain.User) error
}
